name: bus_lnk
description: a Bus app for Metlink
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  dio_http_cache: ^0.2.11
  flutter_map: ^0.11.0
  flutter_map_marker_cluster: ^0.3.4
  fuzzy: 0.3.0
  intl: 0.16.1
  import_sorter: ^4.4.1
  localstorage: ^3.0.6
  scroll_to_index: ^1.0.6
  url_launcher: 5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  linter: ^0.1.129
    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
